devstack gate fixes for bagpipe ML2
Really enable bagpipe ML2 when ENABLE_BAGPIPE_L2 is set.
Define Q_AGENT early enough.
Properly set ENABLE_BAGPIPE_L2 in devstack gate init script.

Change-Id: I1f0e5d923d93322b659c3a8c72f67c45054ee7be

diff --git a/devstack/override-defaults b/devstack/override-defaults
--- a/devstack/override-defaults
+++ b/devstack/override-defaults
@@ -5,7 +5,15 @@ NETWORKING_BAGPIPE_DIR=$DEST/networking-bagpipe
 if [[ "$Q_AGENT" =~ "bagpipe-linuxbridge" ]] ; then
   echo "Using 'Q_AGENT='bagpipe-linuxbridge' in local.conf is deprecated, please replace by enable_service q-agt-bagpipe"
   Q_AGENT=linuxbridge
-  enable_service q-agt-bagpipe
+fi
+
+ENABLE_BAGPIPE_L2=$(trueorfalse False ENABLE_BAGPIPE_L2)
+if [[ "$ENABLE_BAGPIPE_L2" == "True" ]]; then
+  Q_AGENT=linuxbridge
+
+  # Temporary, until we don't need a different main() that the linuxbridge agent's
+  echo "Patching $TOP_DIR/lib/neutron_plugins/linuxbridge_agent to use neutron-bagpipe-linuxbridge-agent binary"
+  perl -i -pe 's:^( *)AGENT_BINARY=.*:${1}AGENT_BINARY="\$NEUTRON_BIN_DIR/neutron-bagpipe-linuxbridge-agent":' $TOP_DIR/lib/neutron_plugins/linuxbridge_agent || die $LINENO "Could not patch linuxbridge agent devstack plugin"
 fi
 
 pushd $NETWORKING_BAGPIPE_DIR
